# Generated by Django 5.1.1 on 2025-03-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('describtion', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=521)),
            ],
        ),
    ]
